<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="PREM-OPTIMUS" failures="0" tests="1" name="excelDataDriven.DataManagementwithDataProviders" time="0.000" errors="1" timestamp="07 Jun 2022 07:36:48 GMT" skipped="0">
  <testcase classname="excelDataDriven.DataManagementwithDataProviders" name="sampleTest" time="0.000">
    <error message="
Method public void excelDataDriven.DataManagementwithDataProviders.sampleTest(java.lang.String,java.lang.String,java.lang.String,java.lang.String) requires a @DataProvider named : dp" type="org.testng.TestNGException">
      <![CDATA[org.testng.TestNGException: Method public void excelDataDriven.DataManagementwithDataProviders.sampleTest(java.lang.String,java.lang.String,java.lang.String,java.lang.String) requires a @DataProvider named : dpat org.testng.internal.Parameters.findDataProvider(Parameters.java:513)at org.testng.internal.Parameters.handleParameters(Parameters.java:691)at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:914)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </error>
  </testcase> <!-- sampleTest -->
</testsuite> <!-- excelDataDriven.DataManagementwithDataProviders -->
